import { BatchData } from "./types";

export const BATCH_DATA: Record<string, BatchData> = {
  "DAKH-2024-AP-001": {
    batchId: "DAKH-2024-AP-001",
    productName: "Tiger Prawns",
    variety: "Penaeus monodon (Black Tiger)",
    weight: "500g",
    grade: "L1 (21–25 count/kg)",
    farm: "Sri Lakshmi Aqua Farm",
    pondId: "POND-NLR-007",
    location: "Nellore, Andhra Pradesh",
    district: "Nellore District",
    waterSource: "Brackish water, tidal creek fed",
    coords: "14.4426° N, 79.9865° E",
    pondArea: "2.4 hectares",
    harvestDate: "12 Nov 2024",
    processingDate: "13 Nov 2024",
    labDate: "14 Nov 2024",
    packagedDate: "15 Nov 2024",
    labStatus: "Passed",
    labName: "Eurofins Food Testing India Pvt Ltd, Hyderabad",
    antibioticResult: "Not Detected (< 0.001 ppm)",
    heavyMetals: "Below permissible limits",
    microbialCount: "TVC < 1×10⁵ CFU/g — Safe",
    fssaiCompliant: "Yes — Reg. 10013022000041",
    tempRange: "0°C to 4°C",
    tempMaintained: "100% Compliant",
    storageFacility: "DAKH Cold Room, Nellore Facility",
    tempScore: 98,
  },
  "DAKH-2024-AP-002": {
    batchId: "DAKH-2024-AP-002",
    productName: "Chitti Royyalu",
    variety: "Litopenaeus vannamei (Pacific White)",
    weight: "500g",
    grade: "M2 (41–50 count/kg)",
    farm: "Coastal Blue Aqua Pvt Ltd",
    pondId: "POND-GTR-003",
    location: "Guntur, Andhra Pradesh",
    district: "Guntur District",
    waterSource: "Saline water, bore well supplemented",
    coords: "15.9129° N, 80.3371° E",
    pondArea: "1.8 hectares",
    harvestDate: "18 Nov 2024",
    processingDate: "18 Nov 2024",
    labDate: "19 Nov 2024",
    packagedDate: "20 Nov 2024",
    labStatus: "Passed",
    labName: "SGS India Pvt Ltd, Vijayawada",
    antibioticResult: "Not Detected (< 0.001 ppm)",
    heavyMetals: "Below permissible limits",
    microbialCount: "TVC < 5×10⁴ CFU/g — Safe",
    fssaiCompliant: "Yes — Reg. 10013022000041",
    tempRange: "0°C to 3°C",
    tempMaintained: "100% Compliant",
    storageFacility: "AquaChill Cold Storage, Guntur",
    tempScore: 100,
  },
  "DAKH-2024-AP-003": {
    batchId: "DAKH-2024-AP-003",
    productName: "Frozen Peeled Shrimp",
    variety: "L. vannamei — Peeled & Deveined",
    weight: "500g",
    grade: "PD (Peeled & Deveined)",
    farm: "DAKH Processing Unit",
    pondId: "POND-VJW-MULTI",
    location: "Vijayawada, Andhra Pradesh",
    district: "Krishna District",
    waterSource: "Multiple certified pond sources",
    coords: "16.5062° N, 80.6480° E",
    pondArea: "Processing Unit — 1,200 sq.ft.",
    harvestDate: "10 Nov 2024",
    processingDate: "22 Nov 2024",
    labDate: "23 Nov 2024",
    packagedDate: "24 Nov 2024",
    labStatus: "Passed",
    labName: "TÜV SÜD South Asia, Hyderabad",
    antibioticResult: "Not Detected",
    heavyMetals: "Below permissible limits",
    microbialCount: "Pathogen Free — HACCP Certified",
    fssaiCompliant: "Yes — Reg. 10013022000041",
    tempRange: "-18°C (Frozen)",
    tempMaintained: "100% Compliant",
    storageFacility: "DAKH Freeze Unit, Vijayawada",
    tempScore: 96,
  },
};

export function getBatch(id: string): BatchData | null {
  return BATCH_DATA[id] ?? null;
}

export const ALL_BATCHES = Object.values(BATCH_DATA);
